from .Boughton import *
from .Chapman import *
from .CM import *
from .Eckhardt import *
from .EWMA import *
from .five_day import *
from .Fixed import *
from .Furey import *
from .ihacres import *
from .LH import *
from .Local import *
from .Slide import *
from .strict import *
from .UKIH import *
from .Willems import *
